=== ijovana/XML-project/data/schemas/propis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl/grddl.xsl"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.parlament.gov.rs/propisi"
    xmlns:pr="http://www.parlament.gov.rs/propisi" xmlns="http://www.w3.org/ns/rdfa#"
    xmlns:pred="http://www.parlament.gov.rs/predicate/">

    <xs:element name="propis">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="deo" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="glava" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="pr:odeljak" maxOccurs="unbounded"
                                            minOccurs="0"/>
                                    </xs:sequence>
                                    <xs:attribute name="broj" form="unqualified" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="[MDCLXVI]*(\.)?"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="naslov">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="\p{Lu}+\s?\p{Lu}*"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="naziv" use="optional">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\p{Lu}+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="redni_broj" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="naziv">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute default="pred:naziv" name="property" use="optional"/>
                                <xs:attribute default="xs:string" name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mesto">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute default="pred:mesto" name="property"/>
                                <xs:attribute default="xs:string" name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="datum_donosenja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute default="pred:datum_donosenja" name="property"/>
                                <xs:attribute default="xs:date" name="datatype"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:string"/>
            <xs:attribute name="status" type="xs:string"/>
            <xs:attribute name="about" type="xs:string"/>
            <xs:attribute name="stanje" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="clan">
        <xs:complexType mixed="false">
            <xs:sequence>
                <xs:element name="naslov" type="xs:string"> </xs:element>
                <xs:element name="opis" nillable="true">
                    <xs:complexType mixed="false"/>
                </xs:element>
                <xs:element name="sadrzaj" form="qualified" maxOccurs="1" minOccurs="1">
                    <xs:complexType mixed="false">
                        <xs:choice maxOccurs="1" minOccurs="1">
                            <xs:element maxOccurs="unbounded" name="stav" minOccurs="1">
                                <xs:complexType mixed="false">
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="tacka" minOccurs="1">
                                            <xs:complexType mixed="false">
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="podtacka"
                                                  minOccurs="1">
                                                  <xs:complexType mixed="false">
                                                  <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="alineje"
                                                  minOccurs="1">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:pattern value="\-\s.*"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  </xs:sequence>
                                                  <xs:attribute name="naziv">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:pattern value="\(\d+\).*"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:attribute>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="naziv">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:string">
                                                  <xs:pattern value="(\d)+\).*"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:pattern value="\p{Nd}"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="link">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="broj" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\p{N}\."/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="naziv" type="xs:string" use="optional"/>
            <xs:attribute name="ID" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:element maxOccurs="unbounded" ref="pr:clan" minOccurs="1"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="pr:odeljak"> </xs:element>
            </xs:choice>
            <xs:attribute name="redni_broj" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\p{N}+\."/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="naziv" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\p{Lu}.*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="ID" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ijovana/XML-project/data/propis/015d867f-49f4-40db-bf0a-b4fa3d5e4cec.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<propis xmlns="http://www.parlament.gov.rs/propisi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" naziv="Krivicni zakonik" ID="015d867f-49f4-40db-bf0a-b4fa3d5e4cec" xsi:schemaLocation="http://www.parlament.gov.rs/propisi file:/C:/Users/Mima/Documents/GitHub/XML-project/data/propis.xsd">
    <deo naziv="OPSTI">
        <glava broj="I" naslov="OSNOVNE ODREDBE">
            <odeljak redni_broj="1." naziv="DDDD">
                <clan broj="1.">
                    <naslov>Nema kriviï¿½nog dela niti kazne bez zakona</naslov>
                    <opis/>
                    <sadrzaj>
                        <stav id="1">
                            <tacka naziv="1)">
<podtacka naziv="(1)">
    <alineje>- a</alineje>
</podtacka>
                            </tacka>
                        </stav>
                    </sadrzaj>
                </clan>
            </odeljak>
        </glava>
    </deo>
</propis>

=== ijovana/XML-project/data/propis/39f9e8b9-7b41-4c81-98f5-bb39f5f65cb7.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<propis xmlns="http://www.parlament.gov.rs/propisi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" naziv="Krivicni zakonik" ID="39f9e8b9-7b41-4c81-98f5-bb39f5f65cb7" xsi:schemaLocation="http://www.parlament.gov.rs/propisi file://home/kristina/Desktop/XMLProj/XML-project/data/propis.xsd">
    <deo naziv="OPSTI">
        <glava broj="I" naslov="OSNOVNE ODREDBE">
            <odeljak redni_broj="1." naziv="DDDD">
                <clan broj="1.">
                    <naslov>Nema kriviï¿½nog dela niti kazne bez zakona</naslov>
                    <opis/>
                    <sadrzaj>
                        <stav id="1">
                            <tacka naziv="1)">
<podtacka naziv="(1)">
    <alineje>- a</alineje>
</podtacka>
                            </tacka>
                        </stav>
                    </sadrzaj>
                </clan>
            </odeljak>
        </glava>
    </deo>
</propis>

=== ijovana/XML-project/data/xsl-fo/propis2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="propis.xsl"?>
<propis xmlns="http://www.parlament.gov.rs/propisi" naziv="KRIVIČNI ZAKONIK" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.parlament.gov.rs/propisi file:/data/propis.xsd">
    <deo naziv="OPŠTI DEO" redni_broj="1.">
        <glava broj="I" naslov="OSNOVNE ODREDBE">
            <odeljak redni_broj="1." naziv="Odeljak1">
                <clan broj="1." naziv="">
                    <naslov>Nema krivičnog dela niti kazne bez zakona</naslov>
                    <opis>Nikome ne može biti izrečena kazna ili druga krivična sankcija za delo koje pre   nego što je učinjeno zakonom nije bilo određeno kao krivično delo, niti mu se može izreći kazna  ili druga krivična sankcija koja zakonom nije bila propisana pre nego što je krivino delo učinjeno.</opis>
                    <sadrzaj>
                        <stav id="1">
                            <tacka naziv="1) ksdfkmsdk">
<podtacka naziv="(1) sdfs">
    <alineje>- a</alineje>
</podtacka>
                            </tacka>
                        </stav>
                    </sadrzaj>
                </clan>
            </odeljak>
        </glava>
    </deo>
</propis>

=== ijovana/XML-project/data/propis/a7a976a6-be67-4c03-908c-6ff1edff561a.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<propis xmlns="http://www.parlament.gov.rs/propisi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" naziv="Krivični zakonik" ID="a7a976a6-be67-4c03-908c-6ff1edff561a" xsi:schemaLocation="http://www.parlament.gov.rs/propisi file://home/kristina/Desktop/XMLProj/XML-project/data/propis.xsd">
    <deo naziv="Naziv dela" redni_broj="1.">
        <glava broj="1." naslov="Naslov glave">
            <odeljak redni_broj="1." naziv="Naziv odeljka">
                <clan broj="1." naziv="Naziv clana">
                    <naslov>Naslov clana</naslov>
                    <opis/>
                    <sadrzaj>
                        <stav id="Id stava">
                            <tacka naziv="Naziv tacke">
<podtacka naziv="Naziv podtacke">
    <alineje>Alineja ima tekst..</alineje>
</podtacka>
                            </tacka>
                        </stav>
                    </sadrzaj>
                </clan>
            </odeljak>
        </glava>
    </deo>
</propis>

=== ijovana/XML-project/data/propis/bf1070ff-0f1a-4008-9572-7d25f568b49d.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<propis xmlns="http://www.parlament.gov.rs/propisi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" naziv="Krivicni zakonik2" ID="bf1070ff-0f1a-4008-9572-7d25f568b49d" xsi:schemaLocation="http://www.parlament.gov.rs/propisi file:/C:/Users/Mima/Documents/GitHub/XML-project/data/propis.xsd">
    <deo naziv="OPSTI2">
        <glava broj="I" naslov="OSNOVNE ODREDBE2">
            <odeljak redni_broj="1." naziv="DDDD">
                <clan broj="1.">
                    <naslov>Nema kriviï¿½nog dela niti kazne bez zakona</naslov>
                    <opis/>
                    <sadrzaj>
                        <stav id="1">
                            <tacka naziv="1)">
<podtacka naziv="(1)">
    <alineje>- a</alineje>
</podtacka>
                            </tacka>
                        </stav>
                    </sadrzaj>
                </clan>
            </odeljak>
        </glava>
    </deo>
</propis>
